### ISSUE TITLE
QueryBuilder extract string part from body field

### ISSUE THREAD

**Issue by marcoberri** [SigNoz/signoz#6473]
## Describe the solution you'd like
Hi,
I have a body field in Log like this :

`  "body": "[PROFILE][RPT 8.0 (ABC)][ClientRPT][executeGET][9 ms]\nArgs: delay=null, packetLossRateTest=null, xptUplinkModcod=null),[Date:\"Fri, 08 Nov 2024 21:40:32 GMT\", Content-Type:\"application/json\", Transfer-Encoding:\"chunked\"]>\n Error: no-error",`

Is possible extract from QueryBuilder only the part of the string (example 9 ms) for show only this value in graph o list?

tnx

**Comment by srikanthccv** [comment]
Please extract out the details to attribtes and you can run any aggregation queries on the extracted out attributes https://signoz.io/docs/logs-pipelines/introduction/

**Comment by marcoberri** [comment]
Hi @srikanthccv  thank you for the reply
I have a question after a read document.
I use a log explorer to extract value
![image](https://github.com/user-attachments/assets/b2eb4d85-3d71-4410-9ca5-74178636caa4)
If i use the same filters in pipeline configuration the response example is empty
![image](https://github.com/user-attachments/assets/817346a6-6693-4f37-8055-b579ac80933e)

**Comment by marcoberri** [comment]
I resolved with add this filter on Pipeline
![image](https://github.com/user-attachments/assets/619360f9-706d-4566-8910-05ae3ebe104b)


is a issues?

tnx

**Comment by pranay01** [comment]
@marcoberri So, was your issue resolved? Or it still persists? 

Please close this issue if it is resolved
