### ISSUE TITLE
[v0.76.1] Constant "Oops !!! Something went wrong"

### ISSUE THREAD

**Issue by KieranP** [SigNoz/signoz#7340]
Just upgraded from 0.76.0 to 0.76.1 and starting to see a ton of "Oops !!! Something went wrong" errors. I cleared by cookies, session, and local storage, and still seeing these pop up at least on 50% of page loads. It's inconsistent, sometimes the page loads, sometimes it doesn't. I tried downgrading to 0.76.0 but still seeing the issues.

**Comment by grandwizard28** [comment]
Hey @KieranP,
Thanks for promptly reporting this!

We're working on an active fix for this. We should have it soon!

Meanwhile v0.76.0 should work perfectly! I understand the frustration behind the release. If you could follow the same cache clear steps in v0.76.0, it should work!

**Comment by KieranP** [comment]
@grandwizard28 I rolled back to 0.76.0 and cleared my cache, but oddly the issues persist. Was there a migration that might have run for 0.76.1 that 0.76.0 isn't compatible with perhaps? Either way, I'll leave it in 0.76.1 until the fix is released.

**Comment by grandwizard28** [comment]
Hey @KieranP,
It should be fixed in [v0.76.2](https://github.com/SigNoz/signoz/releases/tag/v0.76.2).

**Comment by MattiDeGrauwe** [comment]
@grandwizard28 seems to be still present on the latest release

**Comment by grandwizard28** [comment]
Hey @MattiDeGrauwe,
Did you try clearing the browser cache and logging in again?

**Comment by MattiDeGrauwe** [comment]
> Hey [@MattiDeGrauwe](https://github.com/MattiDeGrauwe), Did you try clearing the browser cache and logging in again?

Emptying the browser cache did indeed resolve it this time.

**Comment by KieranP** [comment]
I have updated to 0.76.2 and cleared my browser cache and it does appear to be a lot more stable. I have seen the "Oops !!! Something went wrong" once since, but have been unable to replicate it.
