### ISSUE TITLE
Loading metrics names in alerts create/edit taking ~10s per keyboard press

### ISSUE THREAD

**Issue by KieranP** [SigNoz/signoz#8479]
Trying to filter by metrics names is taking a long time (around 10s on average).

The video demonstrates:

https://github.com/user-attachments/assets/cb556423-f86e-43f3-b4c4-822615c612dc

**Comment by srikanthccv** [comment]
Should be fixed with https://github.com/SigNoz/signoz/pull/8229.

**Comment by KieranP** [comment]
@srikanthccv Just updated to 0.89.0, and while improved, still not as quick as it needs to be (still taking 5s for network request to complete).

https://github.com/user-attachments/assets/57fe3c2b-fce5-4455-a7c8-e49e8c1deeeb
